"""The atelier 4 session with the client — what decides whether each step of an attack succeeds.

The intake questionnaire already covers the technical posture at length (exposure,
MFA, EDR, backups, logging). What it never asks is how those pieces hold together
under an attack in progress: whether a provider's access is controlled, how far a
compromised workstation reaches, whether anyone would notice, whether the backups
survive an attacker who became administrator. A sub-agent that does not know has to
say so, and the likelihood carries that doubt — so the questions are put in session
first, and only those the dossier does not already answer.

Five questions, one per decisive link of a path (enter through a third party, move
up to the critical systems, go unnoticed, destroy the way back, take the data out).
They are authored, not sourced: §18 specifies the fan-out and says nothing about an
atelier 4 interview. Usable and unvalidated, like ateliers 2 and 3's.

The mechanics are shared (mission_context/session.py): asked through an injected
HumanInterface, never generated by a model, none of them blocking, a skip kept with
its justification (§8) and not asked again.
"""

from __future__ import annotations

from ebios_rm.mission_context.priority_matrix import FollowUpQuestion
from ebios_rm.mission_context.session import SessionQuestion, ask_questions, pending_questions
from ebios_rm.workshops.workshop1_cadrage.human_interface import HumanInterface
from ebios_rm.workshops.workshop4_scenarios_operationnels.models import Workshop4Input

# Ordered along an attack path: get in, move up, stay unseen, destroy, leave with the data.
SESSION_QUESTIONS: tuple[SessionQuestion, ...] = (
    SessionQuestion(
        "acces_prestataires",
        "Comment vos prestataires et partenaires accèdent-ils à vos systèmes : comptes nominatifs ou "
        "partagés, authentification forte, accès ouvert en permanence ou à la demande, connexions tracées ?",
        "Un accès tiers permanent et partagé est l'entrée la plus directe des attaques qui passent par "
        "votre écosystème.",
    ),
    SessionQuestion(
        "cloisonnement_administration",
        "Depuis le poste d'un salarié, qu'est-ce qui est joignable : les serveurs métier, les consoles "
        "d'administration, l'annuaire ? Les administrateurs utilisent-ils un poste ou un compte dédié ?",
        "Mesure la distance entre un poste compromis et vos systèmes critiques.",
    ),
    SessionQuestion(
        "delai_detection",
        "Si un compte était utilisé anormalement cette nuit, qui s'en apercevrait, et au bout de combien de temps ?",
        "Une attaque que personne ne voit a le temps d'aller jusqu'au bout.",
    ),
    SessionQuestion(
        "isolement_sauvegardes",
        "Un attaquant devenu administrateur pourrait-il aussi effacer ou chiffrer vos sauvegardes ?",
        "Des sauvegardes joignables avec les mêmes droits disparaissent avec le reste lors d'un rançongiciel.",
    ),
    SessionQuestion(
        "controle_flux_sortants",
        "Remarqueriez-vous une sortie massive de données vers l'extérieur, ou des connexions sortantes inhabituelles ?",
        "Sans contrôle de ce qui sort, un vol de données ne déclenche aucune alerte.",
    ),
)


def session_questions(w4_input: Workshop4Input) -> list[FollowUpQuestion]:
    """The atelier 4 session questions the context does not already answer."""
    return pending_questions(SESSION_QUESTIONS, w4_input)


def ask_session_questions(w4_input: Workshop4Input, human: HumanInterface) -> Workshop4Input:
    """Run the atelier 4 session and return the enriched input."""
    return ask_questions(SESSION_QUESTIONS, w4_input, human)
